feat: tlb first implementation

diff --git a/tlb-func-base.in b/tlb-func-base.in
--- a/tlb-func-base.in
+++ b/tlb-func-base.in
@@ -1,7 +1,7 @@
 #!/bin/sh
-# tlp - Base Functions
+# tlb - Base Functions
 #
-# Copyright (c) 2023 Thomas Koch <linrunner at gmx.net> and others.
+# Copyright (c) 2023 Alessio Molinari <levnikmyskin at github.com> and others.
 # SPDX-License-Identifier: GPL-2.0-or-later
 
 # shellcheck disable=SC2034
@@ -9,15 +9,15 @@
 # ----------------------------------------------------------------------------
 # Constants
 
-readonly TLPVER="@TLPVER@"
+readonly TLBVER="@TLBVER@"
 
-readonly RUNDIR=@TLP_RUN@
-readonly VARDIR=@TLP_VAR@
+readonly RUNDIR=@TLB_RUN@
+readonly VARDIR=@TLB_VAR@
 
-readonly CONF_DEF=@TLP_CONFDEF@
-readonly CONF_DIR=@TLP_CONFDIR@
-readonly CONF_USR=@TLP_CONFUSR@
-readonly CONF_OLD=@TLP_CONF@
+readonly CONF_DEF=@TLB_CONFDEF@
+readonly CONF_DIR=@TLB_CONFDIR@
+readonly CONF_USR=@TLB_CONFUSR@
+readonly CONF_OLD=@TLB_CONF@
 readonly CONF_RUN="$RUNDIR/run.conf"
 
 readonly FLOCK=flock
@@ -26,12 +26,12 @@ readonly LAPMODE=laptop_mode
 readonly LOGGER=logger
 readonly MKTEMP=mktemp
 readonly MODPRO=modprobe
-readonly READCONFS=@TLP_TLIB@/tlp-readconfs
+readonly READCONFS=@TLB_TLIB@/tlb-readconfs
 readonly SYSTEMCTL=systemctl
 readonly TPACPIBAT=@TPACPIBAT@
 readonly UDEVADM=udevadm
 
-readonly TLPRDW=tlp-rdw
+readonly TLBRDW=tlb-rdw
 
 readonly LOCKFILE=$RUNDIR/lock
 readonly LOCKTIMEOUT=2
@@ -53,7 +53,7 @@ readonly RE_PS_IGNORE='sbs-charger|hidpp_battery|hid-'
 
 readonly DEBUG_TAGS_ALL="arg bat cfg disk lock nm path pm ps rf run sysfs udev usb"
 
-readonly TLP_SERVICES="tlp.service"
+readonly TLB_SERVICES="tlb.service"
 readonly PPD_SERVICE="power-profiles-daemon.service"
 readonly RFKILL_SERVICES="systemd-rfkill.service systemd-rfkill.socket"
 
@@ -79,13 +79,13 @@ do_exit () { # cleanup and exit  -- $1: rc
 echo_debug () { # write debug msg if tag matches -- $1: tag; $2: msg;
     [ "$_nodebug" = "1" ] && return 0
 
-    if wordinlist "$1" "$TLP_DEBUG"; then
-        $LOGGER -p debug -t "tlp" --id=$$ -- "$2" > /dev/null 2>&1
+    if wordinlist "$1" "$TLB_DEBUG"; then
+        $LOGGER -p debug -t "tlb" --id=$$ -- "$2" > /dev/null 2>&1
     fi
 }
 
 echo_message () {
-    # output message according to TLP_MSG_LEVEL
+    # output message according to TLB_MSG_LEVEL
     # $1: message
     # $2: loglevel for syslog (default: warning)
 
@@ -93,13 +93,13 @@ echo_message () {
     if [ "$_bgtask" = "1" ]; then
         # called from background task --> use syslog
         if [ -n "$1" ]; then
-            case "$TLP_WARN_LEVEL" in
-                1|3) $LOGGER -p "${2:-warning}" -t "tlp" --id=$$ -- "$1" > /dev/null 2>&1 ;;
+            case "$TLB_WARN_LEVEL" in
+                1|3) $LOGGER -p "${2:-warning}" -t "tlb" --id=$$ -- "$1" > /dev/null 2>&1 ;;
             esac
         fi
     else
         # called from command line task --> use stderr
-        case "$TLP_WARN_LEVEL" in
+        case "$TLB_WARN_LEVEL" in
             2|3)
                 # shellcheck disable=SC2059
                 printf "$1\n" 1>&2
@@ -250,21 +250,8 @@ check_root () {
     fi
 }
 
-check_tlp_enabled () {
-    # check if TLP is enabled in config file
-    # $1: 1=verbose (default: 0)
-    # rc: 0=disabled/1=enabled
-
-    if [ "$TLP_ENABLE" = "1" ]; then
-        return 0
-    else
-        [ "${1:-0}" = "1" ] && echo "Error: TLP power save is disabled. Set TLP_ENABLE=1 in ${CONF_USR}." 1>&2
-        return 1
-    fi
-}
-
 check_rdw_installed () {
-    cmd_exists "$TLPRDW"
+    cmd_exists "$TLBRDW"
 }
 
 check_systemd () {
@@ -293,7 +280,7 @@ check_ppd_active () {
 
 check_services_activation_status () {
     # issue messages for
-    # - TLP service(s) not enabled
+    # - TLB service(s) not enabled
     # - conflicting services enabled
     # rc: 0=no messages/messages issued
 
@@ -301,10 +288,10 @@ check_services_activation_status () {
 
     if check_systemd; then
         cnt=0
-        for su in $TLP_SERVICES; do
+        for su in $TLB_SERVICES; do
             if ! check_service_state "$su" enabled > /dev/null 2>&1 ; then
-                echo_message "Error: TLP's power saving will not apply on boot because $su is not enabled "`
-                            `"--> Invoke 'systemctl enable $su' to ensure the full functionality of TLP." "err"
+                echo_message "Error: TLB's power saving will not apply on boot because $su is not enabled "`
+                            `"--> Invoke 'systemctl enable $su' to ensure the full functionality of TLB." "err"
                 echo_message ""
                 rc=1
             fi
@@ -312,15 +299,15 @@ check_services_activation_status () {
         for su in $RFKILL_SERVICES; do
             if ! check_service_state "$su" masked 2> /dev/null; then
                 if [ "$RESTORE_DEVICE_STATE_ON_STARTUP" = "1" ]; then
-                    echo_message "Warning: TLP's radio device switching on boot may not work as expected because "`
+                    echo_message "Warning: TLB's radio device switching on boot may not work as expected because "`
                                 `"RESTORE_DEVICE_STATE_ON_STARTUP=1 is configured and $su is not masked "`
-                                `"--> Invoke 'systemctl mask $su' to ensure the full functionality of TLP." "err"
+                                `"--> Invoke 'systemctl mask $su' to ensure the full functionality of TLB." "err"
                     echo_message ""
                 elif [ -n "$DEVICES_TO_DISABLE_ON_STARTUP" ] || [ -n "$DEVICES_TO_ENABLE_ON_STARTUP" ]; then
-                    echo_message "Warning: TLP's radio device switching on boot may not work as expected because "`
+                    echo_message "Warning: TLB's radio device switching on boot may not work as expected because "`
                                 `"DEVICES_TO_DISABLE_ON_STARTUP or DEVICES_TO_ENABLE_ON_STARTUP "`
                                 `"is configured and $su is not masked "`
-                                `"--> Invoke 'systemctl mask $su' to ensure the full functionality of TLP." "err"
+                                `"--> Invoke 'systemctl mask $su' to ensure the full functionality of TLB." "err"
                     echo_message ""
                 fi
                 rc=1
@@ -329,6 +316,17 @@ check_services_activation_status () {
     fi
 
     return $rc
+}
+
+check_ac_power () { # check if ac power connected -- $1: function
+
+    if ! get_sys_power_supply ; then
+        echo_debug "bat" "check_ac_power($1).no_ac_power"
+        echo "Error: $1 is possible on AC power only." 1>&2
+        return 1
+    fi
+
+    return 0
 }
 
 # --- Type and value checking
@@ -388,66 +386,66 @@ check_run_flag () { # check flag -- $1: flag name
     return $rc
 }
 
-lock_tlp () { # get exclusive lock: blocking with timeout
-              # $1: lock id (default: tlp)
+lock_tlb () { # get exclusive lock: blocking with timeout
+              # $1: lock id (default: tlb)
               # rc: 0=success/1=failed
 
     create_rundir
     # open file for writing and attach fd 9
     # when successful lock fd 9 exclusive and blocking
     # wait $LOCKTIMEOUT secs to obtain the lock
-    if { exec 9> "${LOCKFILE}_${1:-tlp}" ; } 2> /dev/null && $FLOCK -x -w $LOCKTIMEOUT 9 ; then
-        echo_debug "lock" "lock_tlp($1).success"
+    if { exec 9> "${LOCKFILE}_${1:-tlb}" ; } 2> /dev/null && $FLOCK -x -w $LOCKTIMEOUT 9 ; then
+        echo_debug "lock" "lock_tlb($1).success"
         return 0
     else
-        echo_debug "lock" "lock_tlp($1).failed"
+        echo_debug "lock" "lock_tlb($1).failed"
         return 1
     fi
 }
 
-lock_tlp_nb () { # get exclusive lock: non-blocking
-                 # $1: lock id (default: tlp)
+lock_tlb_nb () { # get exclusive lock: non-blocking
+                 # $1: lock id (default: tlb)
                  # rc: 0=success/1=failed
 
     create_rundir
     # open file for writing and attach fd 9
     # when successful lock fd 9 exclusive and non-blocking
-    if { exec 9> "${LOCKFILE}_${1:-tlp}" ; } 2> /dev/null && $FLOCK -x -n 9 ; then
-        echo_debug "lock" "lock_tlp_nb($1).success"
+    if { exec 9> "${LOCKFILE}_${1:-tlb}" ; } 2> /dev/null && $FLOCK -x -n 9 ; then
+        echo_debug "lock" "lock_tlb_nb($1).success"
         return 0
     else
-        echo_debug "lock" "lock_tlp_nb($1).failed"
+        echo_debug "lock" "lock_tlb_nb($1).failed"
         return 1
     fi
 }
 
-unlock_tlp () { # free exclusive lock
-                # $1: lock id (default: tlp)
+unlock_tlb () { # free exclusive lock
+                # $1: lock id (default: tlb)
 
     # defer unlock for $X_DEFER_UNLOCK seconds -- debugging only
     [ -n "$X_DEFER_UNLOCK" ] && sleep "$X_DEFER_UNLOCK"
 
     # free fd 9 and scrap lockfile
     { exec 9>&- ; } 2> /dev/null
-    rm -f "${LOCKFILE}_${1:-tlp}"
-    echo_debug "lock" "unlock_tlp($1)"
+    rm -f "${LOCKFILE}_${1:-tlb}"
+    echo_debug "lock" "unlock_tlb($1)"
 
     return 0
 }
 
-lockpeek_tlp () { # check for pending lock (by looking for the lockfile)
-                  # $1: lock id (default: tlp)
-    if [ -f "${LOCKFILE}_${1:-tlp}" ]; then
-        echo_debug "lock" "lockpeek_tlp($1).locked"
+lockpeek_tlb () { # check for pending lock (by looking for the lockfile)
+                  # $1: lock id (default: tlb)
+    if [ -f "${LOCKFILE}_${1:-tlb}" ]; then
+        echo_debug "lock" "lockpeek_tlb($1).locked"
         return 0
     else
-        echo_debug "lock" "lockpeek_tlp($1).not_locked"
+        echo_debug "lock" "lockpeek_tlb($1).not_locked"
         return 1
     fi
 }
 
-echo_tlp_locked () { # print "locked" message
-    echo "Error: TLP is locked by another operation." 1>&2
+echo_tlb_locked () { # print "locked" message
+    echo "Error: TLB is locked by another operation." 1>&2
     return 0
 }
 
@@ -555,7 +553,7 @@ select_batdrv () { # source battery feature drivers and
     [ -z "$_batdrv_selected" ] || return 0
 
     # iterate until a matching driver is found
-    for batdrv in @TLP_BATD@/[0-9][0-9]-[a-z]*; do
+    for batdrv in @TLB_BATD@/[0-9][0-9]-[a-z]*; do
         # shellcheck disable=SC1090
         . "$batdrv" || exit 70
 
@@ -571,7 +569,7 @@ select_batdrv () { # source battery feature drivers and
 read_config () { # read all config files and write temporary runconf file
     # $1: 0=continue/1=quit on error
     # $2: 1=no trace
-    # rc: 0=ok/5=tlp.conf missing/6=defaults.conf missing/7=file creation error
+    # rc: 0=ok/5=tlb.conf missing/6=defaults.conf missing/7=file creation error
     # retval: config parameters;
     #         _conf_tmp: runconf
     local rc=0
@@ -583,7 +581,7 @@ read_config () { # read all config files and write temporary runconf file
     else
         tmpdir=${TMPDIR:-/tmp}
     fi
-    if _conf_tmp=$($MKTEMP -p "$tmpdir" "tlp-run.conf_tmpXXXXXX"); then
+    if _conf_tmp=$($MKTEMP -p "$tmpdir" "tlb-run.conf_tmpXXXXXX"); then
         # external perl script: merge all config files to $cf
         if [ "$2" = "1" ]; then
             $READCONFS --outfile "$_conf_tmp" --notrace; rc=$?
@@ -619,7 +617,7 @@ parse_args4config () { # parse command-line arguments: everything after the
     while [ $# -gt 0 ]; do
         if [ $dflag -eq 1 ]; then
             # delimiter was passed --> sanitize and parse argument:
-            #   quotes stripped by the shell calling tlp
+            #   quotes stripped by the shell calling tlb
             #   format is PARAMETER=value
             #   PARAMETER allows 'A'..'Z' and '_' only, may end in a number (_BAT0)
             #   value allows  'A'..'Z', 'a'..'z', '0'..'9', ' ', '-', '_', '.', ':'
@@ -667,7 +665,7 @@ load_modules () { # load kernel module(s) -- $*: modules
 
     # verify module loading is allowed (else explicitly disabled)
     # and possible (else implicitly disabled)
-    [ "${TLP_LOAD_MODULES:-y}" = "y" ] && [ -e /proc/modules ] || return 0
+    [ "${TLB_LOAD_MODULES:-y}" = "y" ] && [ -e /proc/modules ] || return 0
 
     # load modules, ignore any errors
     # shellcheck disable=SC2048
@@ -715,7 +713,7 @@ get_sys_power_supply () {
     #   1. AC chargers
     #   2. Batteries
     #   3. USB
-    # $TLP_PS_IGNORE may be used to ignore one or more power source classes
+    # $TLB_PS_IGNORE may be used to ignore one or more power source classes
 
     local bs ps_ignore psrc psrc_name
     local ac0seen=
@@ -729,7 +727,7 @@ get_sys_power_supply () {
         return "$_syspwr"
     fi
 
-    ps_ignore=$(toupper "$TLP_PS_IGNORE")
+    ps_ignore=$(toupper "$TLB_PS_IGNORE")
     for psrc in /sys/class/power_supply/*; do
         # -f $psrc/type not necessary - read_sysf() handles this
         psrc_name="${psrc##*/}"
@@ -796,7 +794,7 @@ get_sys_power_supply () {
                 # check battery status
                 bs="$(read_sysf "$psrc/status")"
                 if [ "$bs" != "Discharging" ] && [ "$1" = "auto" ] && [ -z "$wait" ]; then
-                    # when command is 'tlp auto', not "Discharging" might be caused by lagging battery status updates
+                    # when command is 'tlb auto', not "Discharging" might be caused by lagging battery status updates
                     # --> recheck every 0.1 secs for 1.5 secs (or user value in deciseconds) max
                     # use delay loop only once
                     wait="$X_PS_WAIT_DS"
@@ -811,7 +809,7 @@ get_sys_power_supply () {
                 fi
                 case "$bs" in
                     Discharging)
-                        if ! lockpeek_tlp tlp_discharge; then
+                        if ! lockpeek_tlb tlb_discharge; then
                             # battery status "Discharging" means battery mode ...
                             _syspwr=1
                             echo_debug "ps" "get_sys_power_supply(${psrc_name}).bat_discharging: syspwr=$_syspwr; wait=$wait"
@@ -858,9 +856,9 @@ get_persist_mode () { # get persistent operation mode
     local rc=1
     _persist_mode="none"
 
-    if [ "$TLP_PERSISTENT_DEFAULT" = "1" ]; then
+    if [ "$TLB_PERSISTENT_DEFAULT" = "1" ]; then
         # persistent mode = configured default mode
-        case $(toupper "$TLP_DEFAULT_MODE") in
+        case $(toupper "$TLB_DEFAULT_MODE") in
             AC)  _persist_mode=0; rc=0 ;;
             BAT) _persist_mode=1; rc=0 ;;
         esac
@@ -869,168 +867,3 @@ get_persist_mode () { # get persistent operation mode
     return $rc
 }
 
-get_power_mode () {
-    # get current operation mode
-    # $1: command
-    # rc: 0=AC/1=battery
-    # similar to get_sys_power_supply(),
-    # but maps unknown power source to TLP_DEFAULT_MODE or returns
-    # persistent mode when enabled
-
-    get_sys_power_supply "$1"
-    local rc=$?
-
-    if get_persist_mode; then
-        # persistent mode
-        rc=$_persist_mode
-    else
-        # non-persistent mode, use current power source
-        if [ $rc -eq 2 ]; then
-            # unknown power supply, use configured default mode
-            case $(toupper "$TLP_DEFAULT_MODE") in
-                AC)  rc=0 ;;
-                BAT) rc=1 ;;
-                *)   rc=0 ;; # use AC if none or invalid mode
-            esac
-        fi
-    fi
-
-    return $rc
-}
-
-compare_and_save_power_state() { # compare $1 to last saved power state,
-    # save $1 afterwards when different
-    # $1: new state 0=ac, 1=battery
-    # rc: 0=different, 1=equal
-    local lp
-
-    # intercept invalid states
-    case $1 in
-        0|1) ;; # valid state
-        *) # invalid new state --> return "different"
-            echo_debug "ps" "compare_and_save_power_state($1).invalid"
-            return 0
-            ;;
-    esac
-
-    # read saved state
-    lp=$(read_sysf $PWRRUNFILE)
-
-    # compare
-    if [ -z "$lp" ] || [ "$lp" != "$1" ]; then
-        # saved state is nonexistent/empty or is different --> save new state
-        create_rundir
-        write_sysf "$1" $PWRRUNFILE
-        echo_debug "ps" "compare_and_save_power_state($1).different: old=$lp"
-        return 0
-    else
-        # touch file for last run
-        touch $PWRRUNFILE
-        echo_debug "ps" "compare_and_save_power_state($1).equal"
-        return 1
-    fi
-}
-
-clear_saved_power_state() { # remove last saved power state
-
-    rm -f $PWRRUNFILE 2> /dev/null
-
-    return 0
-}
-
-check_ac_power () { # check if ac power connected -- $1: function
-
-    if ! get_sys_power_supply ; then
-        echo_debug "bat" "check_ac_power($1).no_ac_power"
-        echo "Error: $1 is possible on AC power only." 1>&2
-        return 1
-    fi
-
-    return 0
-}
-
-echo_started_mode () { # print operation mode -- $1: 0=ac mode, 1=battery mode
-    if [ "$1" = "0" ]; then
-        printf "TLP started in AC mode"
-    else
-        printf "TLP started in battery mode"
-    fi
-    if [ "$_manual_mode" != "n" ]; then
-        printf " (manual).\n"
-    else
-        printf " (auto).\n"
-    fi
-
-    return 0
-}
-
-set_manual_mode () { # set manual operation mode
-    # $1: 0=ac mode, 1=battery mode
-    # retval: $_manual_mode (0=ac, 1=battery)
-
-    if [ "$1" != "0" ] && [ "$1" != "1" ]; then
-        echo_debug "pm" "set_manual_mode($1).invalid"
-        return 1
-    fi
-
-    create_rundir
-    if write_sysf "$1" $MANUALMODEFILE; then
-        _manual_mode="$1"
-        echo_debug "pm" "set_manual_mode($1).ok"
-        return 0
-    else
-        echo_debug "pm" "set_manual_mode($1).write_error"
-        return 1
-    fi
-}
-
-clear_manual_mode () { # remove manual operation mode
-    # retval: $_manual_mode (none)
-
-    rm -f $MANUALMODEFILE 2> /dev/null
-    _manual_mode="n"
-
-    echo_debug "pm" "clear_manual_mode"
-    return 0
-}
-
-get_manual_mode () { # get manual operation mode
-    # rc: 0=active/1=inactive
-    # retval: $_manual_mode (0=ac, 1=battery, a=active, n=inactive)
-    local rc=1
-    _manual_mode="n"
-
-    if [ -f $MANUALMODEFILE ]; then
-        # read mode file
-        if _manual_mode=$(read_sysf $MANUALMODEFILE); then
-            case $_manual_mode in
-                0|1) rc=0 ;;
-                *) _manual_mode="n" ;;
-            esac
-        else
-            # cannot read mode file - possible cause:
-            #   tlp-stat -s is running without root privilege and the file is not world readable
-            #   because tlp ac/bat is invoked with sudo when creating the file and thereby a
-            #   restrictive umask applies; see https://github.com/linrunner/TLP/issues/702
-            # -> manual mode is active but operation mode cannot be determined
-            _manual_mode="a"
-            rc=0
-        fi
-    fi
-    return $rc
-}
-
-# --- Misc Checks
-
-check_laptop_mode_tools () { # check if lmt installed -- rc: 0=not installed, 1=installed
-    if cmd_exists $LAPMODE; then
-        echo 1>&2
-        echo "***Warning: laptop-mode-tools detected, this may cause conflicts with TLP." 1>&2
-        echo "            Please uninstall laptop-mode-tools." 1>&2
-        echo 1>&2
-        echo_debug "pm" "check_laptop_mode_tools: yes"
-        return 1
-    else
-        return 0
-    fi
-}
